#define MAJOR 1
#define MINOR 17
#define PATCH 1
#define BUILD 26


// #define VERSION MACROS
#define VERSION MAJOR.MINOR
#define VERSION_AR MAJOR,MINOR,PATCH,BUILD
#define VERSION_STR MAJOR##.##MINOR##.##PATCH##.##BUILD

#define REQUIRED_VERSION 2.20
#define REQUIRED_CBA_VERSION {3,18,4}
#define REQUIRED_ACE_VERSION {3,20,0}
